spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=my_db;encrypt=true;trustServerCertificate=true
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: SA
    password: todnqjrj1!